query getProducts($first: Int!, $after: String) {
  products(first: $first, after: $after) {
    edges {
      node {
        id
        title
        descriptionHtml
        vendor
        productType
        tags
        images(first: 1) {
          edges {
            node {
              id
              originalSrc
              altText
            }
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
mutation productCreate($product: ProductCreateInput!, $media: [CreateMediaInput!]) {
  productCreate(product: $product, media: $media) {
    product {
      id
      title
      handle
      variants(first: 10) {
        edges {
          node {
            id
            title
            sku
          }
        }
      }
    }
    userErrors {
      field
      message
    }
  }
}
